/// Qdrant Edge — on-device vector search for Dart and Flutter.
///
/// This is the public surface of the SDK. The implementation is the UniFFI
/// binding generated from the shared `qdrant-edge-ffi` Rust crate (the same
/// crate the Swift and Kotlin SDKs bind), regenerated by `./build.sh`.
///
/// The entry point is [EdgeShard] — open one with `EdgeShard.load(...)` or
/// `EdgeShard.create(...)`, then `update(...)` / `search(...)` / `query(...)`.
library;

export 'src/qdrant_edge_ffi.dart';
